### ISSUE TITLE
too long

### ISSUE THREAD

**Issue by faderzz** [0xsyr0/vx-underground-wordlist#1]
wordlist is too long. 
can someone bruteforce "006c74c6813a6efeabea860b2718ed548eed216a319d76ceb178fc38cba458d1.7z" for me and tell me the password or give the contents of the archive without a password

ty
-me

**Comment by 8c** [comment]
any update on the password?

**Comment by faderzz** [comment]
i started working on cracking the password myself. i will update you guys

**Comment by faderzz** [comment]
still havent found a valid password yet ☹

**Comment by faderzz** [comment]
no results yet

**Comment by faderzz** [comment]
finally cracked the password, the password is infected
